version: '3.1'
services:
  db:
    image: postgres
    container_name: prisma_college
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: prisma
      POSTGRES_USER: root
      POSTGRES_DB: prisma
